FROM debian:12

RUN ln -fs /usr/share/zoneinfo/America/Denver /etc/localtime
RUN dpkg-reconfigure -f noninteractive tzdata

RUN apt-get update -y \
    && apt-get upgrade -y

RUN apt-get install -y git curl sudo tzdata which python3


ENV PYTHONPATH="/root/.config/dotfiles:"
ENV PATH="/root/.local/bin:/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV XDG_CONFIG_HOME="/root/.config"
ENV DOTFILES_DIR="/root/.config/dotfiles"

WORKDIR "/root"

COPY "entrypoint.sh" "/entrypoint.sh"

CMD [ "/entrypoint.sh" ]
ENTRYPOINT [ "/entrypoint.sh" ]