FROM opensuse/tumbleweed:latest

RUN zypper -n update
RUN zypper -n install git sudo awk python3 which

ENV PYTHONPATH="/root/.config/dotfiles:"
ENV PATH="/root/.local/bin:/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV XDG_CONFIG_HOME="/root/.config"
ENV DOTFILES_DIR="/root/.config/dotfiles"

WORKDIR "/root"

COPY "entrypoint.sh" "/entrypoint.sh"

CMD [ "/entrypoint.sh" ]
ENTRYPOINT [ "/entrypoint.sh" ]