.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "DOT\-CAT" "1" "August 2026" ""
.SH "NAME"
\fBdot\-cat\fR \- Dump the contents of dotfile(s) to stdout
.SH "SYNOPSIS"
\fBdot cat\fR [\-h] \fIfile\fR\|\.\|\.\|\.
.SH "DESCRIPTION"
Dump the contents of the dotfile(s) to stdout, emulating the functionality of \fBcat\fR\.
.P
Part of dot(1)\.
.SH "OPTIONS"
.TP
\fB\-h\fR, \fB\-\-h\fR
Show command help\.
.TP
\fIfile\fR
One or more managed files\. Paths are relative to the dotfile repo\.

