extend = '../ruff.toml'
target-version = "py39"
line-length = 110

[lint]
extend-ignore = [
    "UP007",  # Python 3.9 doesn't support the | operator
    "ERA001", # commented-out-code
    "D107"
]

# [lint]
# extend-ignore = [
#     "D107",
# ]